// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Fcg.Catalog.Tests.Bdd.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class FluxoDeCompraFeature : object, global::Xunit.IClassFixture<FluxoDeCompraFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt"), "Features", "Fluxo de compra", "  Como usuario da plataforma FCG\r\n  Quero comprar um jogo do catalogo\r\n  Para que" +
                " ele entre na minha biblioteca", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "FluxoDeCompra.feature"
#line hidden
        
        public FluxoDeCompraFeature(FluxoDeCompraFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/FluxoDeCompra.feature.ndjson", 5);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Compra aprovada adiciona o jogo a biblioteca")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Fluxo de compra")]
        [global::Xunit.TraitAttribute("Description", "Compra aprovada adiciona o jogo a biblioteca")]
        public async global::System.Threading.Tasks.Task CompraAprovadaAdicionaOJogoABiblioteca()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Compra aprovada adiciona o jogo a biblioteca", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("que o administrador cadastrou o jogo \"Aventura Espacial\" com preco 199.90", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.WhenAsync("o usuario cria um pedido para o jogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 10
    await testRunner.ThenAsync("recebo o status 202", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
#line 11
    await testRunner.WhenAsync("o pagamento do pedido e processado como aprovado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 12
    await testRunner.ThenAsync("o pedido fica com status \"Aprovado\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
#line 13
    await testRunner.AndAsync("o jogo aparece na biblioteca do usuario", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Compra rejeitada nao adiciona o jogo a biblioteca")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Fluxo de compra")]
        [global::Xunit.TraitAttribute("Description", "Compra rejeitada nao adiciona o jogo a biblioteca")]
        public async global::System.Threading.Tasks.Task CompraRejeitadaNaoAdicionaOJogoABiblioteca()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Compra rejeitada nao adiciona o jogo a biblioteca", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 15
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
    await testRunner.GivenAsync("que o administrador cadastrou o jogo \"Aventura Espacial\" com preco 7500.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 17
    await testRunner.WhenAsync("o usuario cria um pedido para o jogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 18
    await testRunner.ThenAsync("recebo o status 202", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
#line 19
    await testRunner.WhenAsync("o pagamento do pedido e processado como rejeitado com motivo \"Saldo insuficiente\"" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 20
    await testRunner.ThenAsync("o pedido fica com status \"Rejeitado\" e motivo \"Saldo insuficiente\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
#line 21
    await testRunner.AndAsync("a biblioteca do usuario nao contem o jogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Usuario nao dono nao acessa o pedido de outro")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Fluxo de compra")]
        [global::Xunit.TraitAttribute("Description", "Usuario nao dono nao acessa o pedido de outro")]
        public async global::System.Threading.Tasks.Task UsuarioNaoDonoNaoAcessaOPedidoDeOutro()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Usuario nao dono nao acessa o pedido de outro", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 24
    await testRunner.GivenAsync("que o administrador cadastrou o jogo \"Aventura Espacial\" com preco 199.90", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 25
    await testRunner.AndAsync("o usuario criou um pedido para o jogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 26
    await testRunner.WhenAsync("outro usuario consulta esse pedido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 27
    await testRunner.ThenAsync("recebo o status 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entao ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await FluxoDeCompraFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await FluxoDeCompraFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
